### ISSUE TITLE
Developer Max Package

### ISSUE THREAD

**Issue by bezark** [tecartlab/SPARCK#1]
Hi there! I think your SPARCK Software is really cool! On the site you mention utilizing the SPARCK - DEVELOPER version to work directly within MAX. How would I go about finding that package? I can't seem to locate it within the app.

**Comment by maybites** [comment]
as soon as I push the source online you will be able to download a max package. bear with me, it will take another couple of weeks...

**Comment by bezark** [comment]
No worries! I'm just very interested and excited to dig into it 😄 Thanks for all your hard work!
